"""auto_commit action — commit worktree changes and merge into base_repo main.

Runs after release_review approved. Commits all uncommitted changes in the
worktree onto the pipeline branch, then merges into main with --no-ff.

Skipped if the worktree does not exist or has no changes vs code-loops/base.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from rich.console import Console

from ..stages.prompt import StageContext

console = Console()


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {args[0]} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def _base_repo(stage_def: dict, ctx: StageContext) -> Path:
    if ctx.project_config:
        base = (ctx.project_config.get("project") or {}).get("base_repo")
        if base:
            return Path(base)
    legacy = stage_def.get("base_repo")
    if legacy:
        return Path(legacy)
    raise RuntimeError("auto_commit: base_repo not configured")


def run_auto_commit(stage_def: dict, ctx: StageContext) -> dict:
    wt_path = ctx.task_dir / "worktree" / "wt"
    if not wt_path.exists():
        console.print("  [yellow]auto_commit:[/yellow] no worktree — skip")
        return {"skipped": True, "reason": "no worktree"}

    # Anything uncommitted?
    status = subprocess.run(
        ["git", "-C", str(wt_path), "status", "--porcelain"],
        capture_output=True, text=True,
    ).stdout.strip()

    # Anything ahead of the base tag?
    ahead = subprocess.run(
        ["git", "-C", str(wt_path), "rev-list", "code-loops/base..HEAD", "--count"],
        capture_output=True, text=True,
    ).stdout.strip()

    if not status and ahead == "0":
        console.print("  [dim]auto_commit:[/dim] nothing to ship — skip")
        return {"skipped": True, "reason": "no changes vs base"}

    task_name = ctx.task_dir.name
    branch = f"code-loops/{task_name}"

    if status:
        _git(wt_path, "add", "-A")
        _git(wt_path, "commit",
             "--author=code-loops <code-loops@local>",
             "-m", f"feat: {task_name}\n\nGenerated by code-loops pipeline.")
        console.print(f"  [dim]auto_commit:[/dim] committed worktree changes on {branch}")

    base_repo = _base_repo(stage_def, ctx)
    _git(base_repo, "merge", "--no-ff", branch,
         "-m", f"merge: {task_name} from code-loops pipeline\n\n"
         "Release-manager approved.")
    sha = _git(base_repo, "rev-parse", "--short", "HEAD")
    console.print(f"  [green]auto_commit:[/green] merged {branch} → main ({sha})")
    return {"merged": True, "branch": branch, "sha": sha}
